# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Uncomment this line if you're using Swift
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'StarredGithubRepos' do
pod 'Locksmith', '~> 2.0.8'
pod 'PureLayout', '~> 3.0.1'
end

target 'StarredGithubReposTests' do

end

target 'StarredGithubReposUITests' do

end

