# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Uncomment this line if you're using Swift
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'StarredGithubRepos' do

end

target 'StarredGithubReposTests' do

end

target 'StarredGithubReposUITests' do

end

